### ISSUE TITLE
Missing detail in bullet-points

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/target.en#100]
Issue in ./help/c-integrating-target-with-mac/a4t/analytics-tracking-server.md

There is detail missing from each of the three bullet-points under point #1.

**Comment by mtalbot29** [comment]
Rewrote topic to include the newer Adobe Experience Platform Debugger and Developer Tools.
https://docs.adobe.com/content/help/en/target/using/integrate/a4t/analytics-tracking-server.html
Note: duplicate image is being corrected and will be available shortly.

Thanks for the input!
