### ISSUE TITLE
mboxCreate not valid for at.js 2.x

### ISSUE THREAD

**Issue by JonasVanvoorden** [AdobeDocs/target.en#101]
Issue in ./help/c-recommendations/c-products/entity-attributes.md

Hi,

The example on the page is still using the mboxcreate function. it would probably help for the customers if you mention that this is not possibly anymore with at.js 2.x

Thank you in advance.

Kind regards,
Jonas

**Comment by mtalbot29** [comment]
Thanks for your comment. I added a note to: https://docs.adobe.com/content/help/en/target/using/recommendations/entities/entity-attributes.html
