### ISSUE TITLE
Doesn't detail impact if any of ITP 2.3

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/target.en#104]
Issue in help/c-implementing-target/c-considerations-before-you-implement-target/c-privacy/apple-itp-2x.md

Doesn't detail impact if any of ITP 2.3 - https://webkit.org/blog/9521/intelligent-tracking-prevention-2-3/

**Comment by mtalbot29** [comment]
Thanks for your comment. I have updated the article.
https://docs.adobe.com/content/help/en/target/using/implement-target/before-implement/privacy/apple-itp-2x.html
