### ISSUE TITLE
recommendation: mention that mboxcreate is not usable in at.js2.x anymore. 

### ISSUE THREAD

**Issue by JonasVanvoorden** [AdobeDocs/target.en#105]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/t-mbox-download/orderconfirm-create.md

recommendation: mention that mboxcreate is not usable in at.js2.x anymore. It would be great to add an example how to use get/apply offer.

Thanks in advance,
Jonas

**Comment by mtalbot29** [comment]
Thanks for you comments. I consulted with the engineer and updated the topic. Please see the note at the top of the article. Let me know if this works for you.
