### ISSUE TITLE
Unable to get public-facing IP address by x-cluster-client-ip

### ISSUE THREAD

**Issue by immany** [AdobeDocs/target.en#108]
Issue in ./help/c-target/c-visitor-profile/variables-profiles-parameters-methods.md

"user.header('x-cluster-client-ip')" is described to get public-facing IP address, however this parameter is not working now. User should use "user.header('x-forwarded-for');" to get public-facing IP address instead.

**Comment by mtalbot29** [comment]
Thanks for the input. Fixed:
https://docs.adobe.com/help/en/target/using/audiences/visitor-profiles/variables-profiles-parameters-methods.html
