### ISSUE TITLE
authenticated/unauthenticated

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/target.en#109]
Issue in ./help/c-target/c-visitor-profile/working-with-customer-attributes.md

On the page it says: "If the vst.* parameters are the only thing identifying the visitor, the existing "authenticated" profile will not be fetched as long as authState is UNAUTHENTICATED (0). The profile will only come into play if authState is changed to UNAUTHENTICATED (1)."

Shouldn't it be AUTHENTICATED(1)?

**Comment by mtalbot29** [comment]
Fixed. Thanks for the catch:
https://docs.adobe.com/content/dam/help/target.en/help/c-target/c-visitor-profile/assets/TargetAudience.png
