### ISSUE TITLE
Links go to internal Adobe pages

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/target.en#110]
Issue in help/c-implementing-target/c-api-and-sdk-overview/releases-nodejs.md

The links to the documentation for getOffers() API and create() API method go to an internal Adobe staff only page.

Please share the documentation so that your customers can use these SDKs correctly.

**Comment by mtalbot29** [comment]
Thanks for your comment. Earlier today the links appeared to be not working but they are now. Please let me know if you have further issues/problems access those methods.

**Comment by Brontojoris** [comment]
The url https://git.corp.adobe.com/anischev/target-nodejs-sdk/blob/TNT-33695/README.md#targetclientgetoffers is not one that the public can access.

**Comment by mtalbot29** [comment]
There might be a certificate issue. I am looking into it. Thanks for the heads-up.
