### ISSUE TITLE
passing multi-value attributes out of date

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#111]
Issue in help/c-recommendations/c-algorithms/work-with-multi-value-attributes.md

The section Pass a multi-value mbox parameter in JavaScript list the old deprecated method via mboxCreate as the only option. This should be updated with the targetPageParams method. You can find here: https://docs.adobe.com/content/help/en/target/using/recommendations/entities/custom-entity-attributes.html#section_80FEFE49E8AF415D99B739AA3CBA2A14

It might also be good to include a cross link to that page.

**Comment by mtalbot29** [comment]
Thanks. I updated the topic and will post it later today.
