### ISSUE TITLE
No Delivery API Instructions

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#112]
Issue in ./help/c-recommendations/c-products/custom-entity-attributes.md

The section: Implementing Multi-Value Attributes, list delivery API as an option for passing multi-value attributes but contains no information about it. An example and small explanation are warranted here. Something like:

Over the Delivery API you can pass them in an mbox parameter as a string value containing an escaped JSON array.

`  "execute": {
    "mboxes": [
      {
        "index": 0,
        "name": "first-mbox",
        "parameters": {
          "entity.id": "32323",
          "entity.categoryId": "My Category",
          "entity.MultiValueAttribute": "[\"X\", \"Y\", \"Z\"]"
        }
      }`

**Comment by mtalbot29** [comment]
Ryan, is there any formatting with the JSON array?

**Comment by ryrob30** [comment]
Hey Mark,

I tried to format the json but github seems to ignore it. Trying again. 
```
"execute": {
    "mboxes": [
      {
        "index": 0,
        "name": "first-mbox",
        "parameters": {
          "entity.id": "32323",
          "entity.categoryId": "My Category",
          "entity.MultiValueAttribute": "[\"X\", \"Y\", \"Z\"]"
        }
      }
    ]
  }

**Comment by mtalbot29** [comment]
Perfect. I will update again. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mtalbot29** [comment]
Thanks for your help on this one.
