### ISSUE TITLE
AEM Deeplink Feature has been removed as per TGT-33045

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/target.en#113]
Issue in ./help/c-experiences/c-manage-content/aem-experience-fragments.md

In the video at 4:54, AEM Deeplink is shown which is no longer applicable. Please add the following note:

AEM Deeplink feature has been removed as per TGT-33045

**Comment by mtalbot29** [comment]
Thanks. Added note. Will publish later today.
