### ISSUE TITLE
hard to tell what the param limits are

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/target.en#115]
Issue in ./help/r-troubleshooting-target/target-limits.md

Hi, it's hard to sort out what the limits are by library version on this doc. I would suggest removing this line because later on other information is provided that is more specific to the type of request:

"In-mbox profiles in an mbox request
Limit : 50 profiles.
All profiles after 50 are ignored."

**Comment by mtalbot29** [comment]
Removed that section. Will publish later today. Thanks.
