### ISSUE TITLE
no glossary entry for "visit"

### ISSUE THREAD

**Issue by kwarner-adobe** [AdobeDocs/target.en#116]
Issue in ./help/c-intro/glossary.md

There should be a glossary entry for "visit" that explains that a visit, sometimes called a session, ends after 30 min of inactivity, meaning at least 30 min has passed between server requests to Target.

**Comment by mtalbot29** [comment]
Added entry: https://docs.adobe.com/content/help/en/target/using/introduction/glossary.html#section_0B85CE959BA948CDAC3BAEFB4EEDFAD2
Thanks.
