### ISSUE TITLE
SEO tagging target docs to AEM 

### ISSUE THREAD

**Issue by naomi0705** [AdobeDocs/target.en#12]
Issue in ./help/target-home.md

When I do a search for any target documentation through a search engine like google, its being tagged as AEM and not Target. Please see screen shot. However the links, point to the target product documentation. This is misleading. 
![image](https://user-images.githubusercontent.com/48728754/54625400-997fd000-4a45-11e9-9efc-d0745241634c.png)

**Comment by bbringhu** [comment]
Thanks for logging this issue. We'll look into it.

@mblawrence , @mtalbot29

**Comment by Gipaul** [comment]
We have updated meta and our robots info and this is now fixed.
