### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/target.en#120]
Issue in ./help/cmp-resources-and-contact-information.md

Enhancement ideas and suggestions for the Analytics suite can be added to our Customer Idea Exchange .
The hyper link to Customer Idea Exchange points to a url to omniture, which customers do not have access anymore. can you please update this link to the correct place that customers can raise enhancement requests to Adobe Target?

**Comment by mtalbot29** [comment]
Thanks. Have updated the link to the Target Experience League. Pushing live now. It'll take an hour or two.
