### ISSUE TITLE
Page contains multiple links to what appears to be internal Adobe links

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/target.en#125]
Issue in help/c-implementing-target/c-api-and-sdk-overview/releases-nodejs.md

Page contains multiple links to the domain https://git.corp.adobe.com which when clicked goes to a page saying "Device Verification Error - client cert not provided". Assuming these links are intended for Adobe internal use only?

e.g. https://git.corp.adobe.com/anischev/target-nodejs-sdk/blob/TNT-33695/README.md#targetclientgetoffers

**Comment by mtalbot29** [comment]
Can you try to hit those links again? I'm not sure if the site was temporarily down or something. I can open those links from my home with no Adobe login or VPN.

**Comment by mpspencer** [comment]
Tried again and got the same message after bypassing this browser warning
![Screenshot_20200506-225544](https://user-images.githubusercontent.com/9847041/81192609-0ad56600-8fed-11ea-8a18-0ee80c909a9f.png)

**Comment by mtalbot29** [comment]
Let me ask around. I just had my wife use her computer (we're working from home, as is everyone these days) and she is getting a certificate error on some of the links. I'll keep you updated.

**Comment by mtalbot29** [comment]
Should be good now. Thanks for the heads-up.

https://docs.adobe.com/content/help/en/target/using/implement-target/server-side/releases-nodejs.html
