### ISSUE TITLE
Incorrect description for the triggerView parameter

### ISSUE THREAD

**Issue by bennetrj** [AdobeDocs/target.en#13]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-triggerview-atjs-2.md

When options > page parameter is false, it should not send any notifications to the backend. But in the documentation it is incorrectly stated as it will send notification. Please see the attached screenshot.

<img width="1427" alt="Screen Shot 2019-03-21 at 12 10 08 PM" src="https://user-images.githubusercontent.com/19791189/54767590-d548a000-4bd3-11e9-8645-53d95d61d2c0.png">

**Comment by mtalbot29** [comment]
Fixed:
https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/functions-overview/adobe-target-triggerview-atjs-2.html
