### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by zncd** [AdobeDocs/target.en#131]
The link to recommendations video at the bottom of this section: 
Adobe Target Basics Webinar: Introduction to Recommendations
has the old community URL and does not work. Here is the link to the actual video: https://adobecustomersuccess.adobeconnect.com/p8gt31drhs3e/?OWASP_CSRFTOKEN=4bd6cac5d0806167ee0a5449ba93d6300548d09c922bcb751c38973897a5703a

**Comment by mtalbot29** [comment]
Thanks. I updated the link and am pushing live now. Should be up in ~90 minutes.
