### ISSUE TITLE
Sample includes <b> tags for entity attribute values

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#132]
Issue in ./help/c-recommendations/c-products/entity-attributes.md

Under Use entity attributes there is a sample of code for several of the entity attributes. In the sample each of the values includes a <b> and </b> tag. The values should not include these tags,

**Comment by mtalbot29** [comment]
Fixed. Please see if everything is good. And, thanks for the help.
https://docs.adobe.com/content/help/en/target/using/recommendations/entities/entity-attributes.html
