### ISSUE TITLE
Dependent profile scripts- not recommended

### ISSUE THREAD

**Issue by skandgupt24** [AdobeDocs/target.en#134]
Issue in ./help/target-home.md

Kindly update the documentation https://docs.adobe.com/content/help/en/target/using/audiences/visitor-profiles/profile-parameters.html#section_1389497BB6D84FC38958AE43AAA6E712
 with information as :
Creating dependent profile scripts that is using the result of one profile script in another profile script is not recommended as order of profile scripts execution is not guaranteed.

**Comment by mtalbot29** [comment]
Thanks, added as a bullet point.
