### ISSUE TITLE
Video unavailable/This video is private.

### ISSUE THREAD

**Issue by marlonnelson** [AdobeDocs/target.en#135]
Issue in ./help/c-intro/intro.md

Videos purporting to "provide a basic understanding of how Target, along with other Adobe Experience Cloud solutions, can help your organization achieve its goals" are unavailable.

![image](https://user-images.githubusercontent.com/2924369/87683412-0c3eaf80-c74f-11ea-935c-1f70249e5c63.png)

**Comment by mtalbot29** [comment]
Thanks for the comment. I have removed the videos and will see if I can host them elsewhere to make them embedable in my document.
