### ISSUE TITLE
Adding more examples

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/target.en#137]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

Hi,
Can you add the following as an example to do a pageLoad?

adobe.target.getOffers({
  request: {
    execute : {
      pageLoad : {
        parameters : {}
      }
    }
  }
});

Thanks,
Jonathan

**Comment by mtalbot29** [comment]
Jonathon, can you do the proper indenting. Looks like it was stripped out.

**Comment by mtalbot29** [comment]
I think I got it:

adobe.target.getOffers({
  request: {
    execute: {
      pageLoad: {
        parameters: {},
      },
    },
  },
});

**Comment by mtalbot29** [comment]
Publishing now. Can you check on the formatting in an hour or so (or Monday)?
