### ISSUE TITLE
DNL appears in page

### ISSUE THREAD

**Issue by vikigiurgiu** [AdobeDocs/target.en#14]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/how-to-deployatjs/cmp-implementing-target-using-adobe-launch.md

Search for `DNL` in the page.

**Comment by mtalbot29** [comment]
Fixed. Thanks.
https://docs.adobe.com/help/en/target/using/implement-target/client-side/deploy-at-js/cmp-implementing-target-using-adobe-launch.html
