### ISSUE TITLE
Clarification on last paragraph

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#140]
Issue in ./help/c-target/c-visitor-profile/visitor-profile-lifetime.md

Slack discussion here: https://adobe-acs.slack.com/archives/C0ERPN55W/p1598537524062400

EXCERPT IN QUESTION

> If you have two sites under one client code and a visitor visits both sites, the profile is set to the lifetime of profiles on whichever site was visited last. For example, if Site 1 has an 84-day profile lifetime and Site 2 has a 14-day lifetime, and the visitor visits Site 1 and then Site 2, that visitor’s profile will expire in 14 days of inactivity. If the visitor visits Site 1 after visiting Site 2, the profile will expire in 84 days of inactivity.

Clarify that this is only if one or both sites are implemented with mbox.js which requires a code update after the VPL is updated. Not relevant anyway soon upon mbox.js deprecation, but we should clarify or remove when no longer applicable.

**Comment by mtalbot29** [comment]
Yeah, I'm waiting to see when mbox.js is deprecated. It won't be this weekend as announced.

**Comment by mtalbot29** [comment]
Text now reads:
In the following scenario, assume that one or both sites are implemented with mbox.js, which requires a code update after the profile is updated. If both sites are under one client code and a visitor visits both sites, the profile is set to the lifetime of profiles on whichever site was visited last. For example, if Site 1 has an 84-day profile lifetime and Site 2 has a 14-day lifetime, and the visitor visits Site 1 and then Site 2, that visitor's profile will expire in 14 days of inactivity. If the visitor visits Site 1 after visiting Site 2, the profile will expire in 84 days of inactivity.

https://docs.adobe.com/help/en/target/using/audiences/visitor-profiles/visitor-profile-lifetime.html

**Comment by mtalbot29** [comment]
Thanks, Justine!
