### ISSUE TITLE
AAM Integration

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/target.en#142]
Issue in ./help/c-integrating-target-with-mac/a4t/before-implement.md

Hi,
Can we add in a section here about how when you enabled shared audiences (to get A4T) it also enables sharing audiences between AAM and Target which means clients get charged for each Target call in AAM. We've run into many situations where clients haven't realized this and end up getting charged. 

Thanks,
Jonathan

**Comment by mtalbot29** [comment]
Added section as requested. Thanks for the heads-up.

https://docs.adobe.com/content/help/en/target/using/integrate/a4t/before-implement.html#shared-audiences
