### ISSUE TITLE
A4T troubleshooting documentation needs updated to include at.js 2. x. specific information.

### ISSUE THREAD

**Issue by rylanf** [AdobeDocs/target.en#145]
Issue in help/c-integrating-target-with-mac/a4t/c-a4t-troubleshooting/a4t-troubleshooting.md

Current A4T troubleshooting documentation states “In the Target call, the supplemental ID is contained in the mboxMCSDID parameter”.

With at.js 2. there is no longer a mboxMCSDID parameter in the network call and this ID is now returned in HTTP header under path experienceCloud.analytics.supplementalDataId

See supporting documentation: https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/upgrading-from-atjs-1x-to-atjs-20.html

"mboxMCSDID
(at.js 1. x parameter)
SDID, also known as Supplemental Data ID. Should be passed into experienceCloud > analytics > supplementalDataId ."

Should update the documentation so that it provides details of how to review supplemental ID for both at.js 1. x and at.js 2. x.

**Comment by mtalbot29** [comment]
Is this what you wanted?
https://docs.adobe.com/content/help/en/target/using/integrate/a4t/troubleshoot-a4t/a4t-troubleshooting.html

**Comment by rylanf** [comment]
@mtalbot29 Looks good to me! Good idea to also include call out to use the Adobe Debugger.

**Comment by mtalbot29** [comment]
Thanks for your help with this. I appreciate it.

**Comment by rylanf** [comment]
@mtalbot29 Actually just looked it over again and have the following suggestion to remove any ambiguity. 

Current:
"at.js 2.x : The supplemental ID is returned in the HTTP header as the value for experienceCloud.analytics.supplementalDataId."

Proposed:
at.js 2.x : In the Target call, the supplemental ID is returned in the HTTP header as the value for experienceCloud.analytics.supplementalDataId. In the Analytics call, the supplemental ID is contained in the sdid parameter.

**Comment by mtalbot29** [comment]
Will do.

**Comment by mtalbot29** [comment]
https://docs.adobe.com/content/help/en/target/using/integrate/a4t/troubleshoot-a4t/a4t-troubleshooting.html
