### ISSUE TITLE
A4T now can be used as reporting source for auto-target activities, but this page is not updated

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/target.en#147]
Issue in ./help/c-activities/auto-target-to-optimize.md

The page has this statement:
"The algorithm does not support using Analytics as a data-source or a reporting endpoint."

but in Sep 2020, Adobe have just release support of A4T for auto-target activities, refer to current release note:
https://docs.adobe.com/content/help/en/target/using/release-notes/release-notes.html

so should above statement be updated now?

**Comment by mtalbot29** [comment]
Thanks, you are correct. I removed that statement. I am publishing now and it should be live in about an hour.
