### ISSUE TITLE
Need to update the Analytics permissions description

### ISSUE THREAD

**Issue by immany** [AdobeDocs/target.en#148]
Issue in ./help/c-integrating-target-with-mac/a4t/account-reqs.md

Now there is no permission group like "All Report Access" and "Web Services Access" group in Analytics since Analytics has migrated the permission settings to Admin Console.

So we should change the description to let the customer set the needed access permission to the Report Suite and Web Service Access.

**Comment by mtalbot29** [comment]
According to client care, this article is now up to date. Thanks.
