### ISSUE TITLE
Adobe Target Help File Error - PowerPoint file cannot open

### ISSUE THREAD

**Issue by ravinderangelmaya** [AdobeDocs/target.en#152]
Issue in ./help/c-intro/target-welcome-kit-8.md

https://experienceleague.adobe.com/docs/target/using/introduction/welcome/target-welcome-kit-8.html?lang=en#introduction

We’ve included an Executive Summary Results template in Microsoft PowerPoint. 

This PowerPoint file when downloaded does not open; it needs repairing. So I cannot open the file in PowerPoint
[executive-summary.zip](https://github.com/AdobeDocs/target.en/files/5630204/executive-summary.zip)
.

**Comment by mtalbot29** [comment]
Thanks for your comment. I uploaded the file again and it works in Chrome and Safari. You might need to clear cache (or open in incognito). Let me know if you have any further issues.
