### ISSUE TITLE
ERROR The element selector entered does not map to any location on the page. - This is a highly annoying limitation. 

### ISSUE THREAD

**Issue by jonasgoddeeris** [AdobeDocs/target.en#153]
Issue in ./help/c-experiences/c-visual-experience-composer/r-troubleshoot-composer/vec-scenarios.md

Browse functionality is not working properly so cannot create the context with the element visible.
This error is forcing me to write logic myself while a simple set content based on selector would do. 
Sure give me a warning, but why block me completely?
This is the most annoying A/B test tool of them all!

**Comment by mtalbot29** [comment]
Thanks for your input. I forwarded this to the appropriate product manager.
