### ISSUE TITLE
CNAME Help section - First party request form not found/redirected

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/target.en#154]
Issue in ./help/c-implementing-target/c-considerations-before-you-implement-target/implement-cname-support-in-target.md

CNAME Request form is not available on that page
https://docs.adobe.com/content/help/en/core-services/interface/ec-cookies/assets/FPC_Request_Form.xlsx > https://experienceleague.adobe.com/

**Comment by mtalbot29** [comment]
Sorry, this link should work:
https://experienceleague.adobe.com/docs/core-services/assets/FPC_Request_Form.xlsx?lang=en

I will update the documentation. Thanks for the heads-up!

**Comment by mtalbot29** [comment]
Link is fixed in documentation. You might need to refresh.
https://experienceleague.adobe.com/docs/target/using/implement-target/before-implement/implement-cname-support-in-target.html?lang=en#cname-and-adobe-target

Thanks again.
