### ISSUE TITLE
blackslach not showing in page

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#156]
Issue in ./help/c-experiences/c-manage-content/passing-profile-attributes-to-the-html-offer.md

In this sentence:
> When using dynamic attributes in a Recommendations design, you must insert a backslash (‘’) before the dollar sign (‘$’) in order for the dynamic value to render properly

The backslash doesn't show in the ('') where it should be.

**Comment by mtalbot29** [comment]
Thanks. I had to escape the backslash in our new system.
https://experienceleague.adobe.com/docs/target/using/experiences/offers/passing-profile-attributes-to-the-html-offer.html?lang=en#experiences
