### ISSUE TITLE
Update on Target-API limits - With the MAR-21 Release the API limits for Target will (likely) change - please update documentation

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/target.en#157]
Issue in ./help/r-troubleshooting-target/target-limits.md

Hello Doc-Team,

please review this Adobe Internal Ticket for details [0].

With the MAR-21 Release the API limits for Target will (likely) change - please update documentation.

Please sync with engineering (Alexandru) on the changes to be made, and when.

Thanks and cheers
Robert

[0] https://jira.corp.adobe.com/browse/TGT-38304?focusedCommentId=24183779&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24183779

**Comment by mtalbot29** [comment]
Thanks, was updated for the last release:
https://experienceleague.adobe.com/docs/target/using/troubleshoot/target-limits.html?lang=en#offer-size
