### ISSUE TITLE
Incomplete and mis-leading statement about customer attributes.

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/target.en#16]
Hey team.

This article is reporting the following statement: "Customer Attributes require the use of the Experience Cloud ID (ECID)."
Alas that's not wrong, still it is highly mis-leading.
In fact customer attributes requires:

- The usage of the ECID Service.
- The usage of a customer ID, typically related to the customer attributes data source (eg. CRM ID, Loyalty ID, etc).

This is clearly described in the following articles:

- "If you are using the Experience Cloud ID service, you must set a Customer ID and Authentication State to use customer attributes in targeting" - [Ref1](https://experienceleague.adobe.com/docs/target/using/audiences/visitor-profiles/working-with-customer-attributes.html?lang=en#using-the-experience-cloud-id-service).
- "The Alias ID corresponds to the additional [Customer IDs](https://experienceleague.adobe.com/docs/id-service/using/reference/authenticated-state.html?lang=en) that you can associate with each visitor." - [Ref2](https://experienceleague.adobe.com/docs/core-services/interface/services/customer-attributes/t-crs-usecase.html?lang=en).

May I suggest to change that initial statement into: "Customer Attributes require the use of the Experience Cloud ID (ECID) and of a source ID, such as the CRM ID or the Loyalty ID".

Issue in ./help/main/c-implementing-target/c-considerations-before-you-implement-target/c-methods-to-get-data-into-target/bulk-profile-update-api.md

**Comment by mtalbot29** [comment]
Thanks for the correction.
