### ISSUE TITLE
Need info on at.js 2.x added

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#162]
Issue in ./help/c-target/c-audiences/c-target-rules/geo.md

This section: How can I test my activities as if I’m a user coming from a different location?
Only gives info relevant to at.js 1.x. We should provide info on at.js 2.x also. Here's something I've written up in slack to help answer some questions:
To override your IP address with at.js 2.x you can install a browser extension/plugin (like X-Forwarded-For Header for Chrome or Firefox) that allows you to pass the _x-forwarded-for_ header in your page requests.

**Comment by mtalbot29** [comment]
Added your text here: https://experienceleague.adobe.com/docs/target/using/audiences/create-audiences/categories-audiences/geo.html?lang=en#section_DD308A53AF0F48FA8C81423580561FE7

Thanks for the input!
