### ISSUE TITLE
Order of Libraries in Prereqs for A4T

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target.en#17]
Issue in ./help/c-integrating-target-with-mac/a4t/before-implement.md

It would be helpful to ensure the order of the files listed is consistent and they are also in the recommended order of deployment on the page to reinforce the importance of proper order of operations, i.e.:

**Requirements Needed for A4T**
This integration requires that you implement the following library versions (or newer) if you do not plan on using redirect offers with A4T:
- Experience Cloud Visitor ID Service: visitorAPI.js version 1.8.0
- Adobe Target (depending on your implementation): at.js version 0.9.1 or mbox.js version 61 |  
- Adobe Analytics: appMeasurement.js version 1.7.0

**Requirements Needed for Redirect Offers Using A4T**
To use redirect offers with A4T, you must implement the following library versions (or newer):
- Experience Cloud Visitor ID Service: visitorAPI.js version 2.3.0 or later
- Adobe Target: at.js version 1.6.2 or later
- Adobe Analytics: appMeasurement.js version 2.1
**Note:** The mbox.js library does not support redirect offers with A4T. Your implementation must use at.js.

**Comment by mtalbot29** [comment]
Changed order as directed:
https://docs.adobe.com/content/help/en/target/using/integrate/a4t/before-implement.html
