### ISSUE TITLE
A4T now supports Auto-Allocate and Auto-Target

### ISSUE THREAD

**Issue by immany** [AdobeDocs/target.en#172]
Issue in ./help/c-activities/target-activities-guide.md

In the section "Benefits and considerations", please remove "Auto- Allocate cannot consume reports in A4T." and "Auto Target cannot consume reports in A4T." since A4T supports Auto-Allocate and Auto-Target now. Please prefer https://experienceleague.adobe.com/docs/target/using/integrate/a4t/a4t-at-aa.html?lang=en#integrate

**Comment by mtalbot29** [comment]
Thanks for the correction. I have removed those two sentences.

**Comment by immany** [comment]
Thanks!
