### ISSUE TITLE
Extra quotation Mark

### ISSUE THREAD

**Issue by motoyamakai** [AdobeDocs/target.en#174]
Issue in ./help/c-recommendations/t-create-recs-activity/previewing-and-launching-your-recommendations-activity.md

There appears to be an extra quotation mark on the note in the "Using QA links to preview Recommendations" section at the bottom of the section:

While in QA mode, browsing the site will not affect your profile’s Recently Viewed Items or Recently Purchased Items." This behavior occurs by design to avoid unintentional pollution of production behavioral data. To preview results from a Recently Viewed Items or User-Based Recommendations criteria, first browse the site outside of QA mode, then use the same session to open a QA mode link.

**Comment by mtalbot29** [comment]
Thanks for the correction.
