### ISSUE TITLE
Add link to I/O integration page

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#175]
Issue in ./help/c-experiences/c-manage-content/aem-experience-fragments.md

Step 1 only links to the legacy AEM/Target integration method. It should also include a link to the Adobe I/O version for AEM 6.5.2. https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/integration-ims-adobe-io.html?lang=en

**Comment by mtalbot29** [comment]
Thanks for the information. I've updated the documentation here:
https://experienceleague.adobe.com/docs/target/using/experiences/offers/aem-experience-fragments.html?lang=en
