### ISSUE TITLE
Query String parameters - incorrect supported status

### ISSUE THREAD

**Issue by paran-k** [AdobeDocs/target.en#176]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/upgrading-from-atjs-1x-to-atjs-20.md

Looking at the matrix table here: https://experienceleague.adobe.com/docs/target/using/implement-target/client-side/at-js-implementation/upgrading-from-atjs-1x-to-atjs-20.html?lang=en#query-string-parameters

**?mboxOverride.browserIp** is labelled as "No" i.e. not supported, but according to product teams it is. I've just tested this my self on at.js 2.4.0 and it does work.

Please update the documentation as a Client is reluctant to upgrade due to features like these no longer being supported.
<img width="687" alt="Screenshot 2021-06-16 at 15 00 46" src="https://user-images.githubusercontent.com/68638891/122233083-ac4b0e80-ceb3-11eb-8fa1-be062dc7524e.png">

**Comment by mtalbot29** [comment]
Thanks for the correction. The doc has been updated and should be live.
