### ISSUE TITLE
out dates edge locations

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#177]
Issue in ./help/c-intro/how-target-works.md

I believe this paragraph is referencing old edge locations (Amsterdam and Hong Kong). They aren't present on the map. I don't believe we have services in those locations anymore.

> Customer site activity data is collected by the closest of seven Edge Clusters. This data is directed to a customer’s pre-determined Central Cluster destination (one of three locations: Oregon, Dublin, Singapore) for processing. Visitor profile data is stored on the Edge Cluster closest to the site visitor. Edge clusters locations include the Central Cluster locations and Virginia, **Amsterdam**, Sydney, Tokyo, and **Hong Kong**.

**Comment by mtalbot29** [comment]
Thanks for the correction. Should be live within minutes.
