### ISSUE TITLE
Recommendation Feeds - Model CSV guide unavailable

### ISSUE THREAD

**Issue by 33tonypapousek** [AdobeDocs/target.en#178]
Howdy,
I'm unable to download the "model csv guide" mentioned in [/help/c-recommendations/c-products/feeds.md](https://github.com/AdobeDocs/target.en/blob/master/help/c-recommendations/c-products/feeds.md)

[Its URL](https://recspm2.experiencecloud.adobe.com/content/mac/default/target/files/EntityFileUploadTemplate.csv) just redirects to whichever instance I'm using at the time.

Could you host this file statically on GitHub or a similar public service?

**Comment by mtalbot29** [comment]
Thanks for the heads-up, Tony. See if it works now (I relocated the file).

https://experienceleague.adobe.com/docs/target/using/recommendations/entities/feeds.html?lang=en

**Comment by 33tonypapousek** [comment]
@mtalbot29 - Sure thing. Works perfectly now, thanks!
