### ISSUE TITLE
Steps to implement on device via at.js 2.5

### ISSUE THREAD

**Issue by alexbishop010** [AdobeDocs/target.en#179]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/on-device-decisioning/on-device-decisioning.md

I've followed all of the recommended steps but I still see network requests being made on every page, and I'm not clear on exactly how I can validate everything. I'm assuming that I should expect to see a network request on the first page load that goes and retrieves the artifact from the CDN but I'm not seeing this either.

I have everything configured https://sandboxanalytics.s3.eu-north-1.amazonaws.com/Target/target-test-site.html; in window.targetGlobalSettings I have 
{
    "bodyHidingEnabled": false,
    "decisioningMethod": "on-device",
    "clientCode": "ecapacityasemeapartn",
    "imsOrgId": "36F940615A9E7F130A495C85@AdobeOrg",
    "artifactLocation": "https://assets.adobetarget.com/ecapacityasemeapartn/production/v1/rules.json"
}

I tried adding artifactLocation to see if that would help, based on how the node.js setup works that I've done previously

**Comment by mtalbot29** [comment]
Can you log an issue with support? I'll follow up with support if they have any documentation additions/corrections.
