### ISSUE TITLE
Character limit for entity.id and productpurchaseid.

### ISSUE THREAD

**Issue by itnbala** [AdobeDocs/target.en#181]
Issue in ./help/r-troubleshooting-target/target-limits.md

Hi Team,

In one of our recent implementation, we came across a situation where orderconfirmation mbox is failing due to long productpurchaseid length. Error message is "Errors: field - [execute.mboxes[0].order.purchasedProductIds] - purchasedProductId 'XXX' cannot exceed 50 characters;

Looking into this document on limitation, i could see that "entityID parameters" has character limit of 1000, i believe this is entity.id. But entityids in purchasedProductId comma separated can't be more than 47 characters. Which is contradictory? Can you please clarify on this?

Also, documentation says comma separated value exceeding 47 characters will be truncated but receiving error message as cannot exceed 50 characters.

Let me know if you have any questions.

Thanks,
Bala
![Screenshot 2021-07-02 at 12 31 46 PM](https://user-images.githubusercontent.com/7146912/124234356-8c614f00-db31-11eb-83a3-99ca05cad5b0.png)
![Screenshot 2021-07-02 at 12 31 20 PM](https://user-images.githubusercontent.com/7146912/124234362-8ec3a900-db31-11eb-94e3-7fa44c079e50.png)
![Screenshot 2021-07-02 at 12 31 27 PM](https://user-images.githubusercontent.com/7146912/124234364-8f5c3f80-db31-11eb-9ca7-ebe734a206d9.png)

**Comment by mtalbot29** [comment]
Thanks for your input. I've worked with product management to update the following sections:

- entity.id
- productPurchasedId parameter

Does this clarify the limits adequately?
