### ISSUE TITLE
Need to add more explanation of consumerId

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/target.en#182]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

consumerId is important in a4t. 
When using getOffers() api, each call will generate a new sdid. If you have multiple mbox requests on the same page, and want to preserve sdid (so that it matches the sdid from target-global-mbox and AA's sdid), you will need to use consumerId paramter. 
If getOffers() include 3 mbox'es, named "mbox1", "mbox2", and "mbox3", then need to include:
consumerId: "mbox1, mbox2, mbox3" in the gerOffers() call. 

Many customers are very confused with how to make A4T to work when using getOffers() api in at.js 2.x. I found the above solution from internal jira: https://jira.corp.adobe.com/browse/TNT-38466

**Comment by mtalbot29** [comment]
Thanks for the information about consumerID. Can you give this a quick review?
https://experienceleague.adobe.com/docs/target/using/implement-target/client-side/at-js-implementation/functions-overview/adobe-target-getoffers-atjs-2.html?lang=en
