### ISSUE TITLE
Updated content for consumerId

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/target.en#183]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

About consumerId, I just reviewed the updated doc:

> Default value is client’s global mbox if not provided. This key is used to generate the supplemental data ID (SDID) used for A4T integration. This key is a unique string per visitor.
When using getOffers(), each call generates a new SDID. If you have multiple mbox requests on the same page, and want to preserve the SDID (so that it matches the SDID from the target-global-mbox and the Adobe Analytics SDID), use the consumerId parameter.
If getOffers() includes three mboxes (named “mbox1”, “mbox2”, and “mbox3”), include: consumerId: "mbox1, mbox2, mbox3" in the getOffers() call.

"This key is a unique string per visitor." - this sentence is incorrect. This key (consumerId) is mbox names, not unique.

**Comment by mtalbot29** [comment]
Does this work?

Default value is client's global mbox if not provided. This key is used to generate the supplemental data ID (SDID) used for A4T integration. This key (consumerId) is not unique.

**Comment by weijiejane** [comment]
Hi,

I think it’s better just to remove that sentence – “This key (consumerId) is not unique.”

Thanks

Jane

From: mtalbot29 ***@***.***>
Date: Thursday, 15 July 2021 at 7:45 am
To: AdobeDocs/target.en ***@***.***>
Cc: Jane Wei ***@***.***>, Author ***@***.***>
Subject: Re: [AdobeDocs/target.en] Updated content for consumerId (#183)

Does this work?

Default value is client's global mbox if not provided. This key is used to generate the supplemental data ID (SDID) used for A4T integration. This key (consumerId) is not unique.

**Comment by mtalbot29** [comment]
Removed sentence as requested.
