### ISSUE TITLE
Update "Recommend Previously Purchased Items" option

### ISSUE THREAD

**Issue by immany** [AdobeDocs/target.en#20]
Issue in ./help/main/c-recommendations/c-algorithms/create-new-algorithm.md

The option name for "(Optional) Slide the Recommend Previously Purchased Items toggle to the “on” position." has been changed to "Allow recently purchased items to be recommended?" And now this option is under Inclusion Rules section, we also should update the screen shot the position of this option.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/33674088/177072561-7d0e1fa7-f655-4343-bb4f-1e34d284c9e3.png">

**Comment by mtalbot29** [comment]
Thanks for the corrections. Please review and let me know if I've missed anything.
https://experienceleague.adobe.com/docs/target/using/recommendations/criteria/create-new-algorithm.html
