### ISSUE TITLE
Mixed Content error in Target

### ISSUE THREAD

**Issue by BevansDesign** [AdobeDocs/target.en#23]
1. This issue has existed for at least a couple years. Is it ever going to get fixed? Doesn't fill me with a lot of confidence in your product if I have to navigate around major (potentially unsafe) errors to use it.

Issue in ./help/c-experiences/c-visual-experience-composer/r-troubleshoot-composer/mixed-content.md

**Comment by mtalbot29** [comment]
Thank you for your feedback. This repository is for Adobe Target documentation and we welcome any feedback about the documentation. Please feel free to contact customer care for issues with the product.

I did forward your concern to the product management team and to a group of consultants.
