### ISSUE TITLE
Invalid Documentation

### ISSUE THREAD

**Issue by seLalit** [AdobeDocs/target.en#23]
Issue in ./help/main/c-target/c-visitor-profile/variables-profiles-parameters-methods.md
![Screenshot 2022-11-08 at 22 01 39](https://user-images.githubusercontent.com/9293999/200674841-2d7aa024-0eb1-452d-bd6a-d53079f30909.png)

user.getLocal(‘param_name’,‘value’); is wrong it should be without value.

**Comment by mtalbot29** [comment]
Thanks for the correction!
