### ISSUE TITLE
pageURL and thumbnailURL

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#24]
Issue in ./help/c-recommendations/c-products/entity-attributes.md

The naming convention of the documentation when it refers to pageUrl and thumbnailUrl is inconsistent with the actual product.

The "sample csv" when downloaded from Adobe Target Recommendations Feed uses
- entity.pageUrl and entity.thumbnailUrl

The documentation refers to it as
- entity.pageURL and entity.thumbnailURL

This has thankfully not caused any issues but it does create for a messy and inconsistent implementation.

**Comment by mtalbot29** [comment]
Thank you! I have corrected the capitalization in both variables.
https://docs.adobe.com/help/en/target/using/recommendations/entities/entity-attributes.html
