### ISSUE TITLE
Link broken for Adobe Target Size Calculator

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/target.en#26]
Issue in ./help/main/c-intro/how-target-works.md

Hi Team, the Link to the Adobe Target Size Calculator seems to be broken and / or not shown as intended (see [this link to Highlight](https://experienceleague.adobe.com/docs/target/using/introduction/how-target-works.html#:~:text=Adobe%20Target%20%5BSample%20Size%20Calculator%5D)). Thank you :)

**Comment by mtalbotgmail** [comment]
Thanks! It should be fixed now.
