### ISSUE TITLE
Add a Q/A to important attributes FAQ

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#27]
Issue in ./help/main/c-reports/c-personalization-insights-reports/important-attributes-report.md

It might be nice to include a Question about what to do if I see an attribute showing up that I don't want the model to consider? Then we could link them to the new API to remove attributes from the model.
https://developer.adobe.com/target/administer/models-api/

**Comment by mtalbotgmail** [comment]
Thanks, Ryan. 

I updated the topic: https://experienceleague.adobe.com/docs/target/using/reports/insights/important-attributes-report.html#models-api

**I see one or more attributes that I don’t want the model to use for training. Can I remove those attributes from the training model?** 

The Models API, also called the Blocklist API, lets users view and manage the list of attributes (also called features) used in machine learning models for Automated Personalization (AP) and Auto-Target (AT) activities. If you want to exclude one or more attributes from being used by the models for AP or AT activities, you can use the Models API to add those attributes to the “blocklist.”

For detailed information, see [Models API overview](https://developer.adobe.com/target/before-administer/models-api/) in the Adobe Target Developer Guide. To use the API to block attributes, see [Models API](https://developer.adobe.com/target/administer/models-api/).
