### ISSUE TITLE
Search Results pages result in non-functional Top Nav buttons

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target.en#3]
Issue in ./help/en/target/search.html?_charset_=UTF-8
When on search results page, topnav links show the current address URL instead of proper URLs. Image attached:
![image](https://user-images.githubusercontent.com/15110214/53580663-c07f6c00-3b41-11e9-907b-4e2bcc5e861a.png)

Regards,
Lester

**Comment by mtalbot29** [comment]
Seems to be fixed. Thanks for the comment.
