### ISSUE TITLE
"Confidence" definition is wrong. It should be "as extreme as the one observed" not "less extreme than the one observed"

### ISSUE THREAD

**Issue by jayakhan** [AdobeDocs/target.en#30]
Issue in ./help/main/c-reports/statistical-methodology/statistical-calculations.md

**Comment by mtalbotgmail** [comment]
Thanks for the correction. The article has been updated.
https://experienceleague.adobe.com/docs/target/using/reports/statistical-methodology/statistical-calculations.html#confidence
