### ISSUE TITLE
Function attributed to incorrect AT.js versions

### ISSUE THREAD

**Issue by bennetrj** [AdobeDocs/target.en#33]
1) adobe.target.applyOffer(options) is available both on AT.js 1.x and 2.x, but is labelled as a AT.js 2.x function.

2) adobe.target.getOffers(options) is an AT.js 2.x function and is not labelled as AT.js 2.x like the rest of the functions.

Please see screenshot.
<img width="1439" alt="Screen Shot 2019-05-16 at 10 12 05 AM" src="https://user-images.githubusercontent.com/19791189/57860921-b32e6100-77c3-11e9-867b-4accdd0872b6.png">

Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/cmp-atjs-functions.md

**Comment by mtalbot29** [comment]
Thanks. Fixed and published.
https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/functions-overview/cmp-atjs-functions.html
