### ISSUE TITLE
Custom Event names confusing

### ISSUE THREAD

**Issue by bennetrj** [AdobeDocs/target.en#34]
Hi Team,

On the section where it talks about at-view-start and at-view-end, can you please mention that these events needs to be fired by customer and they are not part of AT.js custom events. 

Since the name of the event starts with "at-", customer could potentially get confused with out of the box AT.js custom events which also starts with "at-".

Please see the screenshot.

<img width="509" alt="Screen Shot 2019-05-16 at 12 11 52 PM" src="https://user-images.githubusercontent.com/19791189/57869817-d95bfd00-77d3-11e9-8cc6-7e0141622828.png">
 

Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/how-to-deployatjs/target-atjs-single-page-application.md

**Comment by mtalbot29** [comment]
Thanks. Added note and published.

**Comment by mtalbot29** [comment]
https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/deploy-at-js/target-atjs-single-page-application.html#triggerview
