### ISSUE TITLE
Additional information requested

### ISSUE THREAD

**Issue by doecke** [AdobeDocs/target.en#35]
Issue in ./help/c-activities/t-automated-personalization/managing-exclusions.md

Demo of how exclusion groups work. This tells me how to set them up but I'm having trouble understanding what they are exactly. Also, is there a way to exclude Experience Cloud audiences? What's the difference. And is there a way to modify or suppress the data that's available in the Experience Cloud for Sensei to use?

**Comment by mtalbot29** [comment]
Thanks. Let me know if you need anything else.
