### ISSUE TITLE
Contradictory information

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/target.en#35]
Issue in ./help/main/administrating-target/c-user-management/property-channel/property-channel.md

In the Permission view it says that "[The current Target Permissions model has three permission roles](https://experienceleague.adobe.com/docs/target/using/administer/manage-users/enterprise/property-channel.html?lang=en#:~:text=The%20current%20Target%20Permissions%20model%20has%20three%20permission%20roles)" but underneath there is a table that includes a fourth permission, namely the "Publisher" which I believe to be correct so the text seems to be incorrect.

**Comment by mtalbotgmail** [comment]
Thanks for the correction. Unfortunately , the newest permission is not included in the illustrations, so I noted in text that the illustrations don't show that permission.
