### ISSUE TITLE
Some code shouldn't be there

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/target.en#37]
Issue in ./help/main/c-target/c-audiences/c-target-rules/mobile.md
Customers using the Mobile SDK do not need to do anything to apply this functionality. Customers using at.js must [upgrade to at.js version 1.5.0](https://experienceleague.adobe.com/docs/target-dev/developer/client-side/at-js-implementation/target-atjs-versions.html?lang=en) (or later){target=_blank}.  
You should remove the {target=_blank} part

**Comment by mtalbotgmail** [comment]
I add the blank part if they are navigating to another guide. In this case, from the Business Practitioners Guide --> Developers Guide.

**Comment by ericthibeault-adobe** [comment]
Yeah, the blank on the link is totally fine.  It's just that we can see this code in clear text, which is certainly not intended

**Comment by ericthibeault-adobe** [comment]
![image](https://github.com/AdobeDocs/target.en/assets/144477747/8b7dff30-736c-4558-ac98-680f33178a6e)
