### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by SydneeChristensen** [AdobeDocs/target.en#39]
Issue in ./help/main/c-target/c-visitor-profile/profile-parameters.md

In the first table on this page there is a link to the profile API, but it links to the old docs. Should link to here https://experienceleague.adobe.com/docs/target-dev/developer/api/profile-apis/profile-api-overview.html?lang=en

**Comment by mtalbot29** [comment]
Fixed. Thanks, Sydnee.

https://experienceleague.adobe.com/docs/target/using/audiences/visitor-profiles/profile-parameters.html
