### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ryanpizzuto** [AdobeDocs/target.en#40]
Issue in ./help/main/c-integrating-target-with-mac/a4t/a4timplementation.md

Broken link in the below:
Step 3: Create an Edge configuration
Create an Edge configuration using Adobe Experience Platform using the edge configuration tool. Configure the [Analytics and Target edge configuration settings](https://experienceleague.adobe.com/docs/experience-platform/edge/fundamentals/datastreams.html?lang=en).

Link goes to a 404

**Comment by mtalbot29** [comment]
Fixed. Thanks, Ryan.

https://experienceleague.adobe.com/docs/target/using/integrate/a4t/a4timplementation.html
