### ISSUE TITLE
Clarify when a notification is sent

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/target.en#42]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-triggerview-atjs-2.md

TRUE: Default value of page is true. When page=true, notifications are sent to the Target backend for incrementing impression count.
--

Example triggerView() call that will send a notification to the Target backend for incrementing impression count
adobe.target.triggerView("homeView")

These two sentences imply that whenever a triggerView() is invoked (with page: true, which is default) that a notification to Target will be sent "for incrementing impression count." The observed behavior is that notifications are not sent on every triggerView() unless there is an activity experience or activity metric that is associated with that view. Is that the expected behavior? It would help users to understand the expected behavior of at.js 2.x if this were described more explicitly in the documentation. For example "Example triggerView() call that will send a notification to the Target backend for incrementing activity impressions and other metrics. If there is neither an activity experience nor activity metric associated with the view, no notification will be sent."

**Comment by mtalbot29** [comment]
Thanks, Daniel. I have updated the options > page parameter row.
https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/functions-overview/adobe-target-triggerview-atjs-2.html
