### ISSUE TITLE
Inaccurate description of profile expirations

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#43]
Issue in ./help/c-target/c-visitor-profile/visitor-profile-lifetime.md

"By default, visitor profiles are stored for 14 days."

The above statement is incorrect as are other similar statements on the page. I believe the more accurate verbage is something like:  visitor profiles expire after 14 days of inactivity for that visitor.

**Comment by mtalbot29** [comment]
Updated text. Thanks.
