### ISSUE TITLE
at.js 2.x support

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/target.en#44]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/upgrading-from-atjs-1x-to-atjs-20.md

Hi, this page says "Adobe Experience Cloud Debugger is not fully supported in at.js 2.x
Adobe Experience Cloud Debugger # features and Disable and Console Logging tools are supported, but Network Requests and mboxTrace are not supported for at.js 2.x."

Debugger has supported network calls and Target Traces for months now. This limitation should be removed and any other similar content needs to be updated in docs.

**Comment by mtalbot29** [comment]
Removed that section. Thanks.
