### ISSUE TITLE
Adobe Target documentation pages contains Experience Manager in title 

### ISSUE THREAD

**Issue by akasjain** [AdobeDocs/target.en#46]
Issue in ./help/c-activities/t-test-ab/t-test-create-ab/ab-activity-url.md and many other pages

When you search a topic for Adobe Target, then the title of results contains Experience Manager. It should either be **Experience Cloud** or **Adobe Target**

**Comment by akasjain** [comment]
<img width="788" alt="DocTitle" src="https://user-images.githubusercontent.com/33989085/59338660-684f2d00-8d20-11e9-98cf-aeae89e42b6b.PNG">

**Comment by mtalbot29** [comment]
Akash, this is a known issue and has been logged. Thanks for your feedback.

@Gipaul @bbringhu Has there been any traction getting this fixed?

**Comment by Gipaul** [comment]
We have tracked down the erroneous meta and resolved this. Thanks

![image](https://user-images.githubusercontent.com/34586756/59807082-8a5e2780-92ab-11e9-9549-2266fe8da224.png)
