### ISSUE TITLE
Move Limitation

### ISSUE THREAD

**Issue by sijain** [AdobeDocs/target.en#48]
Currently the Limitation Section says
"Move feature
An element cannot be moved outside a container that is followed by a CSS property." 

However, the CSS prooperty is not informed. The details are mentioned @https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=elm&title=VEC+Best+Practices

So, you have provide the property - overflow: hidden

**Comment by mtalbot29** [comment]
Updated: https://docs.adobe.com/content/help/en/target/using/experiences/vec/viztarget-options.html#move

thanks, Sidd
