### ISSUE TITLE
Prehiding snippet description clarification on how at.js works page

### ISSUE THREAD

**Issue by rchiriac** [AdobeDocs/target.en#52]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/c-how-atjs-works/how-atjs-works.md

Step 2. description states "at.js can also be loaded asynchronously with an option prehiding snippet implemented on the page."

Wast it supposed to say "... with an optional prehiding sinppet..."? Or "at.js can also be loaded asynchronously using a prehiding snippet implemented on the page"? 

I mean, is the prehiding snippet optional or is it the option via which at.js can be loaded asynchronously? I assume it's the latter, in which case might be better t osay that "at.js can also be loaded asynchronously using a prehiding snippet implemented on the page".

Thanks

**Comment by mtalbot29** [comment]
According to the PM, is should be "... with an optional prehiding snippet..."

Will publish live later today. Thanks.
