### ISSUE TITLE
consumerId

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#53]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

Hello,

Will you please explain the consumerId parameter further - Is that a string that is the same for the entire implementation, or is that a unique string per visitor?

Asking because I've interpreted it one way and a fellow consultant has interpreted the documentation another way. 

Thank you!

-Justine

**Comment by mtalbot29** [comment]
This key is a unique string per visitor. I've updated the topic and will publish later this evening.

Thanks for your comment.
