### ISSUE TITLE
Escaped characters: Incorrect translation for Japanese

### ISSUE THREAD

**Issue by ashimizu-ccj** [AdobeDocs/target.en#54]
Issue in ./help/c-activities/r-success-metrics/click-tracking.md

There are incorrect Japanese translation for escaped characters matrix:
![image](https://user-images.githubusercontent.com/52389183/60404911-f2840600-9be7-11e9-81ab-2338c4071f6c.png)
"を参照してください。" in 3rd line should be "." (period).
And 2nd "#" should in 5th line be "[ ]".

**Comment by mtalbot29** [comment]
Sonya Piper in localization will reach out to you directly to remedy this issue. Thanks for reporting.
