### ISSUE TITLE
Deprecated notions still present in glossary

### ISSUE THREAD

**Issue by ndiaconu** [AdobeDocs/target.en#55]
Issue in ./help/c-intro/glossary.md
Should remove the following as they are no longer available in Standard/Premium functionality

optimizing campaign
Ensures the most effective experiences are shown more often by automatically distributing traffic to the best performing segments.

smart targeter profile parameter
Similar to script profile parameter, but predefined to provide useful targeting functionality.

**Comment by mtalbot29** [comment]
Removed those terms. Will publish later today. Thanks.
