### ISSUE TITLE
Link to first-party cookies guide

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#60]
Issue in ./help/c-implementing-target/c-considerations-before-you-implement-target/implement-cname-support-in-target.md

Hi there, what is the link to the referenced "First-Party Cookies Guide"? Is it the Analytics First party cookies guide? Thanks for clarifying.

-Justine

**Comment by justlee-adobe** [comment]
Hi there, 

To further clarify, I found out 

1. The CNAME should accept both HTTP and HTTPS
2. The next step after setting up the CNAME is to update the serverDomain to the new CNAME in at.js

Could we add this in?

Thank you

-Justine

**Comment by mtalbot29** [comment]
Justine, are you talking about this page?
https://marketing.adobe.com/resources/help/en_US/whitepapers/first_party_cookies/adobe_managed_cert_pgm.html

I don't control that page, but I can find out who does.

**Comment by justlee-adobe** [comment]
Hi there,

My logged questions for the documentation are from this page:

https://docs.adobe.com/content/help/en/target/using/implement-target/before-implement/implement-cname-support-in-target.html


Justine Lee  |  Senior Technology Consultant  |  Adobe  |  c. 678.428.6876  |  justlee@adobe.com<mailto:justlee@adobe.com>

**Comment by mtalbot29** [comment]
Thanks, Justine. I confirmed with David Son that what we have now is good.
