### ISSUE TITLE
Incorrect video is on this page about A4T

### ISSUE THREAD

**Issue by iaramsay** [AdobeDocs/target.en#61]
Issue in ./help/c-integrating-target-with-mac/a4t/a4t.md

The video on the page is relating to at.js rather than A4T. I believe the correct content is available here, the Office Hours presentation by Joshua.

https://helpx.adobe.com/customer-care-office-hours/target/analytics-target-A4T-integration.html

regards
Ian, EMEA Clientcare

**Comment by mtalbot29** [comment]
Corrected link. Thanks for the feedback.
