### ISSUE TITLE
New Image Needed

### ISSUE THREAD

**Issue by ryanpizzuto** [AdobeDocs/target.en#62]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/c-how-atjs-works/how-atjs-works.md

The image for the diagram for how at.js 2x works is clearly a screenshot from a PowerPoint as the spell check red squiggly line is under at.js and the Page Load icon has been selected as evidenced by the box around it. 

It should be replaced with a clean image.

**Comment by mtalbot29** [comment]
Updated this and other images:
https://docs.adobe.com/help/en/target/using/implement-target/client-side/at-js/how-atjs-works.html
