### ISSUE TITLE
mbox3rdPartyId vs mbox3rdPartyID

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#65]
Issue in ./help/c-target/c-visitor-profile/3rd-party-id.md

The url parameter is case sensitive and should be mbox3rdPartyId (small d) However all the instances of the name in this doc refer to ...ID.

**Comment by mtalbot29** [comment]
Thanks for the catch. Fixed and pushing to production.

**Comment by mtalbot29** [comment]
Thanks. Pushing live now.
