### ISSUE TITLE
Missing bold text in sample URL (Site Pages)

### ISSUE THREAD

**Issue by baasmannen** [AdobeDocs/target.en#66]
Issue in ./help/c-target/c-audiences/c-target-rules/site-pages.md

The point that contains "Query: The content of the URL after the first question mark (?). For example, the query is shown in bold in the following sample URL:
foo.html?e0a72cb2a2c7"

Nothing is shown in bold in the sample URL :)

**Comment by mtalbot29** [comment]
Thanks. Our new system does not allow for stacked markdown controls (bold inside a sample). I have altered the text to remove the reference to bold.
