### ISSUE TITLE
missing links from help page

### ISSUE THREAD

**Issue by ravinderangelmaya** [AdobeDocs/target.en#68]
https://docs.adobe.com/content/help/en/target/using/reports/conversion-rate.html#concept_0D0002A1EBDF420E9C50E2A46F36629B

missing links are:

To calculate these calculated metrics, download the **Target's Complete Confidence Calculator** Excel file to input the activity's value, or review the **statistical calculations used by Target**.

please see bold references above i.e. **Target's Complete Confidence Calculator** & **statistical calculations used by Target**.

These linked before to : https://marketing.adobe.com/resources/help/en_US/target/target/complete_confidence_calculator.xlsx  but this link is now broken.

**Comment by mtalbot29** [comment]
Updated links to new domain. Thanks for the catch.
