### ISSUE TITLE
Conflicting advice

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/target.en#74]
Issue in ./help/c-activities/automated-traffic-allocation/automated-traffic-allocation.md

Issue in ./help/c-activities/t-test-ab/sample-size-determination.md

This page says to not use the calculator which is the opposite of the calculator page

Calculator page:
https://docs.adobe.com/help/en/target/using/activities/abtest/sample-size-determination.html

See this paragraph:
Target Sample Size Calculator: If you choose to use a manual A/B test rather than Auto-Allocate, the Target Sample Size Calculator helps you determine the sample size needed for a successful test. Continue reading for more information about how to use the calculator.

As opposed to: 
https://docs.adobe.com/content/help/en/target/using/activities/auto-allocate/automated-traffic-allocation.html

Can I use the sample size calculator when using Auto-Allocate to estimate how long the activity will take to identify the winner?
You can use the existing sample size calculator with Bonferroni correction appropriately applied to get an estimate of how long the test will run. In our experiments, we’ve seen the Auto-Allocate activity end much sooner than this sample size.

**Comment by mtalbot29** [comment]
Updated both files:
https://docs.adobe.com/content/help/en/target/using/activities/abtest/sample-size-determination.html
https://docs.adobe.com/content/help/en/target/using/activities/auto-allocate/automated-traffic-allocation.html
