### ISSUE TITLE
sample code has some curly double quotes

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#78]
Issue in ./help/c-implementing-target/c-non-javascript-based-implementation/testing-email-image-adbox.md

The sample code has some curly/styled double quotes mixed in. They can break code and should be replace with all straight quotes.

**Comment by mtalbot29** [comment]
Are you an Adobe employee? If so, I will send you an email that will tell you how to make things easier.

**Comment by ryrob30** [comment]
yes, ryanr@adobe.com

**Comment by mtalbot29** [comment]
Fixed. Thanks!
