### ISSUE TITLE
Request Table type Missing

### ISSUE THREAD

**Issue by chrisakers** [AdobeDocs/target.en#79]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/adobe-target-getoffers-atjs-2.md

The Request table does not specify the accepted types for the fields. The limitations of `order > purchasedProductIds` makes it seem that `purchasedProductIds` should be passed as a string value. Sending a string value results in a 400 error - invalid JSON (itself not a very useful error). Only after viewing the documentation for `sendNotification` was it apparent that `purchasedProductIds` should be an array of strings.

The request table on this page should also have a column for `type`.

**Comment by mtalbot29** [comment]
Thanks for your suggestion. Added link to API doc that contains that information. You can drill down to each field to see its allowable type.
https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/functions-overview/adobe-target-getoffers-atjs-2.html
