### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by bennetrj** [AdobeDocs/target.en#82]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/t-mbox-download/target-download-config-mbox.md

We need to upgrade this document to reflect both mbox.js as well as AT.js download instructions.

**Comment by mtalbot29** [comment]
That topic is specifically for mbox.js and will go away as soon as that library is deprecated. The instructions for at.js are in the at.js section: https://docs.adobe.com/content/help/en/target/using/implement-target/client-side/deploy-at-js/how-to-deployatjs.html
