### ISSUE TITLE
Clarification on "logs out"

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#83]
Issue in ./help/c-target/c-visitor-profile/3rd-party-id.md

Will you clarify "When the visitor logs out, the merged data replaces the previous data associated with the mbox3rdPartyId"?

In Target, what indicates that a visitor is logged out?

For example, is it when there is no value of mbox3rdPartyId, or some other parameter that's passed through the mbox? I'm asking because it's possible for someone to stay logged in but be on a part of the website that doesn't have mbox3rdPartyId implemented.

**Comment by mtalbot29** [comment]
Added note: https://docs.adobe.com/content/help/en/target/using/audiences/visitor-profiles/3rd-party-id.html
