### ISSUE TITLE
Question about reference to "target-global-mbox" in "bodyHidingEnabled"

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/target.en#86]
Issue in help/c-implementing-target/c-implementing-target-for-client-side-web/targetgobalsettings.md

The description for bodyHidingEnabled references "target-global-mbox".
My question here is whether or not this applies to a renamed global mbox? Or does my customer have to use the default global mbox name "target-global-mbox" in order to use the default flicker control described here?

bodyHidingEnabled | Boolean | true | Used to control flicker when target-global-mbox is used to deliver offers created in the Visual Experience Composer , also known as visual offers
-- | -- | -- | --

**Comment by mtalbot29** [comment]
This question would be better addressed in the PM Office Hours wiki.
            https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=ACS&title=Target+Product+North+America+Office+Hours
