### ISSUE TITLE
mis-spelling in Understand the Global mbox ovreview

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/target.en#87]
Issue in ./help/c-implementing-target/c-implementing-target-for-client-side-web/t-mbox-download/c-understanding-global-mbox/understanding-global-mbox.md

On the left navigation bar, there is a mis-spelling in Understand the Global mbox ovreview, which should be "overview"

**Comment by mtalbot29** [comment]
Thanks for the catch. I have corrected the spelling and will publish later today with the 19.10.2 release (October 31, 2019).
