### ISSUE TITLE
QA Script

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/target.en#91]
Issue in ./help/c-target/c-visitor-profile/profile-parameters.md

Can you add this to the script examples. It's the use case to track a user for QA. Customer have asked for this and there's nowhere to point them to.

if (page.param("adobeQA"))
  return page.param("adobeQA");
else if (page.param("adobeqa"))
  return page.param("adobeqa");
else if (mbox.param("adobeQA"))
  return mbox.param("adobeQA");

**Comment by mtalbot29** [comment]
Thanks for the suggestion. Added new example here:
https://docs.adobe.com/help/en/target/using/audiences/visitor-profiles/profile-parameters.html#examples
