### ISSUE TITLE
User Management Misinformation

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/target.en#93]
The currently published [document](https://docs.adobe.com/content/help/en/target/using/administer/manage-users/users/user-management.html) says that only system admins can add users and edit permissions.
This is not how the Admin Console works. System admins, product admins, product profile admins, and group admins have the ability to add users.

On the other hand, only product profile admin or higher can edit the permission type.

**Comment by mtalbot29** [comment]
Thanks. Pushing content live.
