### ISSUE TITLE
Confusing and conflicting content

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/target.en#96]
Issue in ./help/r-troubleshooting-target/target-limits.md

The section on mbox parameter limits on this page is confusing and possibly wrong based on experience and other internal documentation. 

This page says there is a limit of 500 profile parameters per mbox and also a bullet point that doesn't include a number at all for a similar limit. 

I have a client that is reporting an error message that indicates "the number mbox parameters cannot exceed 50", so I think 50 is the right number, but not sure if that's just for profile parameters.

Additionally, another of our help docs here ... 

https://docs.adobe.com/content/help/en/target/using/audiences/visitor-profiles/profile-parameters.html

...says there is a limit of 50 profile attributes per mbox call:

**Comment by mtalbot29** [comment]
Addressed here: https://docs.adobe.com/content/help/en/target/using/troubleshoot/target-limits.html#mbox-parameters
Thanks for your help in getting this updated.
