### ISSUE TITLE
Clarification on when Target might not be required 

### ISSUE THREAD

**Issue by iaramsay** [AdobeDocs/target.en#99]
Issue in ./help/c-implementing-target/c-considerations-before-you-implement-target/implement-cname-support-in-target.md

The page cited above contains FAQs which handle the scenario

'I already have a CNAME implementation for Adobe Analytics, can we use the same certificate or hostname?'

The answer being 'No, Target requires a separate hostname and certificate.'

However on this next page 

https://docs.adobe.com/help/en/target/using/implement-target/before-implement/privacy/apple-itp-2x.html

it states

'Is my current implementation of Target impacted?
In a Safari browser, navigate to your website on which you have a Target JavaScript library. If you see a Target cookie set in the context of a CNAME, such as analytics.company.com , then you are not impacted by ITP 2.1 or 2.2.' 

I believe that the following should be referenced in the first page implement-cname-support-in-target under the FAQ

'Is my current implementation of Target impacted?
In a Safari browser, navigate to your website on which you have a Target JavaScript library. If you see a Target cookie set in the context of a CNAME, such as analytics.company.com , then you are not impacted by ITP 2.1 or 2.2. 

ITP issues can be resolved for Target with just Analytics CNAME. Only in the case of Ad Blocking scenarios where Target is blocked, we will need a separate Target CNAME.'

**Comment by mtalbot29** [comment]
Thanks for your help, Ian. Publishing now.
